version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - logvolume01:/var/log
    links:
      - redis
  db:
    image: mysql/mysql-server
volumes:
  logvolume01: {}
